#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

RUNNER="${JAGC_RUNNER:-echo}"
PORT="${JAGC_PORT:-31415}"
HOST="${JAGC_HOST:-127.0.0.1}"
API_URL="http://$HOST:$PORT"
SERVER_LOG_FILE="${JAGC_SMOKE_SERVER_LOG_FILE:-/tmp/jagc-smoke-server.log}"

fail() {
  echo "$1" >&2
  exit 1
}

assert_succeeded_run() {
  local run_json="$1"
  local status

  status="$(echo "$run_json" | jq -r '.status')"
  if [[ "$status" != "succeeded" ]]; then
    fail "run did not succeed: $run_json"
  fi
}

REMOVE_WORKSPACE_DIR=0
SMOKE_WORKSPACE_DIR="${JAGC_WORKSPACE_DIR:-}"
if [[ -z "$SMOKE_WORKSPACE_DIR" ]]; then
  SMOKE_WORKSPACE_DIR="$(mktemp -d "${TMPDIR:-/tmp}/jagc-smoke-workspace.XXXXXX")"
  REMOVE_WORKSPACE_DIR=1
else
  mkdir -p "$SMOKE_WORKSPACE_DIR"
fi

SMOKE_DATABASE_PATH="${JAGC_DATABASE_PATH:-$SMOKE_WORKSPACE_DIR/jagc.sqlite}"

INVALID_BODY_FILE="$(mktemp "${TMPDIR:-/tmp}/jagc-smoke-invalid.XXXXXX")"
MISMATCH_BODY_FILE="$(mktemp "${TMPDIR:-/tmp}/jagc-smoke-idem-mismatch.XXXXXX")"
MISSING_RUN_BODY_FILE="$(mktemp "${TMPDIR:-/tmp}/jagc-smoke-run-missing.XXXXXX")"

export JAGC_WORKSPACE_DIR="$SMOKE_WORKSPACE_DIR"
export JAGC_DATABASE_PATH="$SMOKE_DATABASE_PATH"
export JAGC_RUNNER="$RUNNER"
export JAGC_PORT="$PORT"
export JAGC_API_URL="$API_URL"

pnpm -s exec tsx src/server/main.ts >"$SERVER_LOG_FILE" 2>&1 &
SERVER_PID=$!

cleanup() {
  kill "$SERVER_PID" >/dev/null 2>&1 || true
  wait "$SERVER_PID" >/dev/null 2>&1 || true

  rm -f "$INVALID_BODY_FILE" "$MISMATCH_BODY_FILE" "$MISSING_RUN_BODY_FILE"

  if [[ "$REMOVE_WORKSPACE_DIR" == "1" ]]; then
    rm -rf "$SMOKE_WORKSPACE_DIR"
  fi
}
trap cleanup EXIT

server_ready=0
for _ in $(seq 1 60); do
  if curl -sf "$API_URL/healthz" >/dev/null; then
    server_ready=1
    break
  fi
  sleep 0.25
done

if [[ "$server_ready" != "1" ]]; then
  fail "smoke server failed to start; see $SERVER_LOG_FILE"
fi

pnpm -s dev:cli health --json | jq -e '.ok == true' >/dev/null

AUTH_JSON="$(pnpm -s dev:cli auth providers --json)"
echo "$AUTH_JSON" | jq -e '.providers | type == "array"' >/dev/null ||
  fail "auth providers response is invalid: $AUTH_JSON"

MESSAGE_JSON="$(pnpm -s dev:cli message "ping" --json)"
RUN_ID="$(echo "$MESSAGE_JSON" | jq -r '.run_id')"

if [[ -z "$RUN_ID" || "$RUN_ID" == "null" ]]; then
  fail "missing run_id in message response: $MESSAGE_JSON"
fi

RUN_RESULT="$(pnpm -s dev:cli run wait "$RUN_ID" --json)"
assert_succeeded_run "$RUN_RESULT"

autogenerated_idempotency_key="smoke-idem-$(date +%s)-$RANDOM"
IDEM_FIRST="$(pnpm -s dev:cli message "idempotent ping" --thread-key "cli:smoke-idempotency" --idempotency-key "$autogenerated_idempotency_key" --json)"
IDEM_SECOND="$(pnpm -s dev:cli message "idempotent ping" --thread-key "cli:smoke-idempotency" --idempotency-key "$autogenerated_idempotency_key" --json)"
IDEM_FIRST_RUN_ID="$(echo "$IDEM_FIRST" | jq -r '.run_id')"
IDEM_SECOND_RUN_ID="$(echo "$IDEM_SECOND" | jq -r '.run_id')"

if [[ "$IDEM_FIRST_RUN_ID" != "$IDEM_SECOND_RUN_ID" ]]; then
  fail "idempotency dedupe failed: first=$IDEM_FIRST second=$IDEM_SECOND"
fi

IDEM_RESULT="$(pnpm -s dev:cli run wait "$IDEM_FIRST_RUN_ID" --json)"
assert_succeeded_run "$IDEM_RESULT"

INVALID_STATUS="$(curl -sS -o "$INVALID_BODY_FILE" -w "%{http_code}" -X POST "$API_URL/v1/messages" -H 'content-type: application/json' --data '{"source":"cli"}')"
if [[ "$INVALID_STATUS" != "400" ]]; then
  fail "expected 400 for invalid payload, got $INVALID_STATUS"
fi
jq -e '.error.code == "invalid_message_payload"' "$INVALID_BODY_FILE" >/dev/null ||
  fail "unexpected invalid payload response: $(cat "$INVALID_BODY_FILE")"

MISMATCH_STATUS="$(curl -sS -o "$MISMATCH_BODY_FILE" -w "%{http_code}" -X POST "$API_URL/v1/messages" -H 'content-type: application/json' -H 'idempotency-key: header-key' --data '{"source":"cli","thread_key":"cli:smoke-idempotency","text":"hello","delivery_mode":"followUp","idempotency_key":"body-key"}')"
if [[ "$MISMATCH_STATUS" != "400" ]]; then
  fail "expected 400 for idempotency mismatch, got $MISMATCH_STATUS"
fi
jq -e '.error.code == "idempotency_key_mismatch"' "$MISMATCH_BODY_FILE" >/dev/null ||
  fail "unexpected idempotency mismatch response: $(cat "$MISMATCH_BODY_FILE")"

MISSING_RUN_STATUS="$(curl -sS -o "$MISSING_RUN_BODY_FILE" -w "%{http_code}" "$API_URL/v1/runs/does-not-exist")"
if [[ "$MISSING_RUN_STATUS" != "404" ]]; then
  fail "expected 404 for unknown run lookup, got $MISSING_RUN_STATUS"
fi
jq -e '.error.code == "run_not_found"' "$MISSING_RUN_BODY_FILE" >/dev/null ||
  fail "unexpected missing run response: $(cat "$MISSING_RUN_BODY_FILE")"

echo "$RUN_RESULT"
